server:
  port:
    8080

spring:
  application:
    name: transaction-categorisation-engine

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/transaction_engine}
    username: ${SPRING_DATASOURCE_USERNAME:app}
    password: ${SPRING_DATASOURCE_PASSWORD:app}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true




